const appConstants = {
    STATE_KEY: 'APP',
    START_LOADING_ACTION_KEY: 'START_LOADING',
    STOP_LOADING_ACTION_KEY: 'STOP_LOADING',
    STORE_USER: 'STORE_USER',
    REMOVE_USER: 'REMOVE_USER',
    REDUCER_USER_KEY: 'USER',
    STORE_VESSELS: 'VESSELS',
    GET_VESSELS: 'GET_VESSELS',
    STORE_TRIPS: 'STORE_TRIPS',
    GET_TRIPS: 'GET_TRIPS',
    STORE_LOCODES: 'STORE_LOCODES',
    BASEURL: 'http://185.247.118.131:80/api', //'http://192.168.1.20:8000/api',
    MAINURL: 'https://crewlog.com/',
    TRIP_DETECTION: 'TRIP_DETECTION',
    STORE_ENDORSEMENT: 'STORE_ENDORSEMENT',
};
export default appConstants;
