const actionType = {
    LOADING: 'LOADING',
    RESET: 'RESET',

    GET: 'GET',
    GET_SUCCESS: 'GET_SUCCESS',
    GET_FAIL: 'GET_FAIL',

    POST: 'POST',
    POST_SUCCESS: 'POST_SUCCESS',
    POST_FAIL: 'POST_FAIL',

    PUT: 'PUT',
    PUT_SUCCESS: 'PUT_SUCCESS',
    PUT_FAIL: 'PUT_FAIL',

    PATCH: 'PATCH',
    PATCH_SUCCESS: 'PATCH_SUCCESS',
    PATCH_FAIL: 'PATCH_FAIL',

    DELETE: 'DELETE',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAIL: 'DELETE_FAIL',

    CHANGE_PAGE: 'CHANGE_PAGE',

    SUBMIT: 'SUBMIT',

    FETCH_DROPDOWN_OPTIONS: 'FETCH_DROPDOWN_OPTIONS',
    FETCH_DROPDOWN_OPTIONS_SUCCESS: 'FETCH_DROPDOWN_OPTIONS_SUCCESS',
    FETCH_DROPDOWN_OPTIONS_FAIL: 'FETCH_DROPDOWN_OPTIONS_FAIL',

    MODAL_OPEN: 'MODAL_OPEN',
    MODAL_CLOSE: 'MODAL_CLOSE',

    SET_APP_ERROR: 'SET_APP_ERROR',
    CLEAR_APP_ERROR: 'CLEAR_APP_ERROR',
};

export default actionType;
